// Flat ESLint config for the Expo app. `eslint-config-expo/flat` is the
// RN/Expo-aware base (react-native, react-hooks, import-resolution rules tuned
// for Metro). CommonJS to match babel.config.js / metro.config.js in this app
// (no "type": "module" in package.json).
const expoConfig = require('eslint-config-expo/flat');

// ── Design-system guards ─────────────────────────────────────────────────────
//
// Before these, mobile source used 31 font sizes, 24 radii and 19 gaps with no
// relationship to each other, 13 unrelated animation durations, and emoji as its
// icon system — which is most of why the UI read as unauthored. Each selector
// below is how one of those happens again, one reasonable-looking line at a time.
// See packages/ui/src/tokens.ts and project-docs/design/motion-spec.md.

/** Raw sizes. Computed values (`sq * 0.14`, `size / 2`) stay allowed: board geometry scales with the board. */
const SCALE_GUARDS = [
  {
    selector:
      "Property[key.name=/^(fontSize|borderRadius|borderTopLeftRadius|borderTopRightRadius|borderBottomLeftRadius|borderBottomRightRadius|gap|rowGap|columnGap)$/][value.type='Literal']",
    message: 'Use FONT_SIZES, RADIUS or SPACING from @gameexplorer/ui instead of a raw number.',
  },
];

/** Motion literals, and animation calls that silently take Reanimated's defaults. */
const MOTION_GUARDS = [
  {
    selector:
      "CallExpression[callee.name=/^with(Timing|Spring)$/] > ObjectExpression > Property[key.name=/^(duration|damping|stiffness|mass)$/][value.type='Literal']",
    message: 'Use the MOTION helpers in src/theme/motion.ts (timing, timeTo, springTo) instead of a literal.',
  },
  {
    selector: "CallExpression[callee.name=/^with(Timing|Spring)$/][arguments.length=1]",
    message:
      "A bare withTiming/withSpring gets Reanimated's defaults, not ours. Pass a MOTION config via src/theme/motion.ts.",
  },
];

/**
 * Emoji in interface text. They draw differently on every platform, cannot take a
 * theme colour, and were this app's icon system until the Phosphor set replaced
 * them. The ranges are emoji-presentation pictographs and symbols; plain
 * typographic marks such as arrows and geometric shapes are left alone. Comments
 * are not checked. Content the player sends (emotes) lives in packages/shared.
 */
const EMOJI = String.raw`/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B1B}\u{2B1C}\u{2B50}\u{2B55}\u{23E9}-\u{23FA}]/u`;
const EMOJI_MESSAGE = 'Use Icon from @/components/ui instead of an emoji or symbol glyph in interface text.';
const EMOJI_GUARDS = [
  { selector: `Literal[value=${EMOJI}]`, message: EMOJI_MESSAGE },
  { selector: `TemplateElement[value.raw=${EMOJI}]`, message: EMOJI_MESSAGE },
  { selector: `JSXText[value=${EMOJI}]`, message: EMOJI_MESSAGE },
];

module.exports = [
  ...expoConfig,
  {
    // Native projects are CNG output (regenerated by `expo prebuild`/EAS) and
    // gitignored; build artifacts and the local Expo cache are not our code.
    ignores: ['android/*', 'ios/*', '.expo/*', 'dist/*', 'node_modules/*'],
  },
  {
    files: ['app/**/*.{ts,tsx}', 'src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': ['error', ...SCALE_GUARDS, ...MOTION_GUARDS, ...EMOJI_GUARDS],
    },
  },
  {
    // Exempt from the emoji guard only. Liquidate's menus, dock and tiles speak
    // a deliberate glyph language shared with web, carried over from its design
    // mock (revisit it as a whole, on both platforms, rather than piecemeal), and
    // tests hold emotes and notation as fixtures. The size and motion guards
    // still apply — a flat-config override replaces the whole rule, so they are
    // restated here.
    files: ['src/liquidate/**/*.{ts,tsx}', 'src/__tests__/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': ['error', ...SCALE_GUARDS, ...MOTION_GUARDS],
    },
  },
];
