// Flat ESLint config for the Expo app. `eslint-config-expo/flat` is the
// RN/Expo-aware base (react-native, react-hooks, import-resolution rules tuned
// for Metro). CommonJS to match babel.config.js / metro.config.js in this app
// (no "type": "module" in package.json).
const expoConfig = require('eslint-config-expo/flat');

module.exports = [
  ...expoConfig,
  {
    // Native projects are CNG output (regenerated by `expo prebuild`/EAS) and
    // gitignored; build artifacts and the local Expo cache are not our code.
    ignores: ['android/*', 'ios/*', '.expo/*', 'dist/*', 'node_modules/*'],
  },
];
