/**
 * Puzzle difficulty calibration — turning "which bot tier solves this" into a
 * rating on the same scale for every game.
 *
 * **The problem this exists to solve.** Chess puzzles arrive from Lichess with
 * a real Glicko rating built from hundreds of thousands of human attempts. The
 * other three games have no such source: their puzzles are mined by our own
 * engines, and nothing about a mined position says how hard a person finds it.
 * Without a common scale, "Club" in the checkers picker and "Club" in the chess
 * picker would be two unrelated claims wearing the same word — which is exactly
 * the equivalence the whole mode is built on.
 *
 * **The method.** Play every bot tier at a puzzle, one attempt per trial, and
 * find the tier where the solve rate crosses one half. That ELO is the puzzle's
 * *bot rating*: the strength at which it is a coin flip. Bot ratings are then
 * mapped onto the human scale by a monotone piecewise-linear fit, anchored on
 * the chess sample where both numbers are known.
 *
 * **What is measurement and what is assumption.** The bot rating is measured.
 * The chess anchor map is fitted to real data. Applying that same map to
 * checkers, reversi and Go is a **modelling assumption** — all four ladders
 * were built by the same method against the same nominal ELO semantics, so "the
 * tier at which a bot solves half the time" is the closest thing to a shared
 * unit these games have, but no human ever rated a checkers puzzle for us. A
 * 1200-rated checkers puzzle therefore claims *"about as hard as a 1200 chess
 * puzzle, by bot-solve equivalence"*, not "1200 checkers Elo". Say it that way
 * anywhere it reaches a player.
 *
 * **Go does not use this at all.** Its bot is MCTS, which averages random
 * playouts, and a life-and-death problem needs an exact reading — measured over
 * all 14 shipped Go puzzles the solve rate was flat at ~0 and faintly *inverted*
 * (the weakest tier scored highest). There is no crossing to interpolate, so Go
 * rates structurally instead; see `goStructuralRating`.
 *
 * The fitted numbers live in `../constants/puzzles/generated/calibration` —
 * generated by `scripts/puzzles/calibrate.mjs`, data only. This module is the
 * hand-written half: the math, and the lookup the miners call.
 */

import { BOT_ELO_BOUNDS, BOT_TIERS, type RatedGameId } from '../constants/botTiers';
import type { PuzzleGame } from './types';

/**
 * The solve rate that defines a puzzle's rating.
 *
 * One half, because that is the point a rating has always meant: the strength
 * at which the outcome is even. Anything else would need a reason.
 */
export const SOLVE_THRESHOLD = 0.5;

/**
 * Trials per tier, and the point at which a unanimous tier stops early.
 *
 * 32 gives a standard error of about 0.088 at p = 0.5 — enough to place a
 * puzzle in a band six tiers wide, and deliberately not enough to claim a
 * precise rating. Most tiers come back unanimous (a bot either sees a tactic or
 * does not), and 8 identical trials is sufficient evidence of that, so the
 * early stop is where nearly all of the machine time is saved.
 */
export const TRIALS_PER_TIER = 32;
export const EARLY_STOP_TRIALS = 8;

// ---------------------------------------------------------------------------
// Solve curve → bot rating
// ---------------------------------------------------------------------------

/**
 * Pool-adjacent-violators: the nearest non-decreasing sequence, by least
 * squares.
 *
 * A solve curve *should* rise with tier strength, and mostly does, but 8–32
 * trials leave enough noise to put a dip in it — and a dip makes the curve
 * cross one half in the wrong place, or twice. Smoothing first removes the
 * whole failure mode for about ten lines, and it cannot invent a crossing that
 * the data does not support: a flat curve stays flat.
 */
export function isotonic(values: readonly number[]): number[] {
  const blocks: { sum: number; count: number }[] = [];
  for (const v of values) {
    blocks.push({ sum: v, count: 1 });
    // Merge backwards while the previous block sits above this one.
    while (blocks.length > 1) {
      const cur = blocks[blocks.length - 1];
      const prev = blocks[blocks.length - 2];
      if (prev.sum / prev.count <= cur.sum / cur.count) break;
      blocks.splice(blocks.length - 2, 2, {
        sum: prev.sum + cur.sum,
        count: prev.count + cur.count,
      });
    }
  }
  return blocks.flatMap((b) => Array<number>(b.count).fill(b.sum / b.count));
}

export interface SolveCurvePoint {
  elo: number;
  /** Solves ÷ trials at this tier. */
  rate: number;
}

export interface BotRating {
  /** The interpolated ELO where the smoothed curve crosses `SOLVE_THRESHOLD`. */
  rating: number;
  /**
   * The weakest tier already solves it at least half the time, so `rating` is
   * an extrapolation below the ladder rather than a crossing measured inside
   * it. Still ordered and still usable — just held to a lower standard of
   * evidence than a rating between two tiers.
   */
  belowFloor: boolean;
  /**
   * The strongest tier never solves it; `rating` is extrapolated above the
   * ladder. A whole game coming back this way means the ladder cannot rate that
   * game at all, which is the Go outcome — a flag rather than a number quietly
   * averaged away.
   */
  aboveCeiling: boolean;
  /** The smoothed curve, kept so the artifact can show its working. */
  smoothed: SolveCurvePoint[];
}

/**
 * The ELO at which this puzzle is a coin flip.
 *
 * Both flags return a usable `rating` as well, because a caller that ignores
 * them still gets the right end of the scale rather than a null it would have
 * to invent a number for.
 */
export function botRatingFromCurve(curve: readonly SolveCurvePoint[]): BotRating {
  if (curve.length === 0) throw new Error('botRatingFromCurve: empty curve');

  const sorted = [...curve].sort((a, b) => a.elo - b.elo);
  const rates = isotonic(sorted.map((p) => p.rate));
  const smoothed = sorted.map((p, i) => ({ elo: p.elo, rate: rates[i] }));

  // Outside the ladder, the rate at the end tier still carries information, and
  // throwing it away was a real defect rather than a conservative choice:
  // pinning every below-floor puzzle to the weakest tier's ELO gave 48 chess
  // puzzles whose Lichess ratings run from 517 to 1478 a single identical
  // rating. It also emptied whole bands — nothing can sit below a floor that
  // every easy puzzle is pinned to.
  //
  // So extrapolate one tier's width, linearly in the end rate: a puzzle the
  // weakest tier solves EVERY time sits a full tier below it, one it solves
  // exactly half the time sits on it. The flag still says this is an
  // extrapolation, because it is.
  if (rates[0] >= SOLVE_THRESHOLD) {
    const spacing = sorted.length > 1 ? sorted[1].elo - sorted[0].elo : 300;
    const t = (rates[0] - SOLVE_THRESHOLD) / (1 - SOLVE_THRESHOLD);
    return {
      rating: Math.round(sorted[0].elo - spacing * t),
      belowFloor: true,
      aboveCeiling: false,
      smoothed,
    };
  }
  if (rates[rates.length - 1] < SOLVE_THRESHOLD) {
    const n = sorted.length;
    const spacing = n > 1 ? sorted[n - 1].elo - sorted[n - 2].elo : 300;
    const t = (SOLVE_THRESHOLD - rates[n - 1]) / SOLVE_THRESHOLD;
    return {
      rating: Math.round(sorted[n - 1].elo + spacing * t),
      belowFloor: false,
      aboveCeiling: true,
      smoothed,
    };
  }

  for (let i = 0; i < rates.length - 1; i++) {
    if (rates[i] < SOLVE_THRESHOLD && rates[i + 1] >= SOLVE_THRESHOLD) {
      // The two rates differ by construction (one is below the threshold and
      // the other is not), so this never divides by zero.
      const t = (SOLVE_THRESHOLD - rates[i]) / (rates[i + 1] - rates[i]);
      return {
        rating: Math.round(sorted[i].elo + t * (sorted[i + 1].elo - sorted[i].elo)),
        belowFloor: false,
        aboveCeiling: false,
        smoothed,
      };
    }
  }

  /* istanbul ignore next — unreachable: the curve is monotone and straddles. */
  throw new Error('botRatingFromCurve: monotone curve straddles the threshold without crossing');
}

/**
 * The range a puzzle RATING may occupy — which is not the range of bot
 * strengths on offer.
 *
 * `BOT_ELO_BOUNDS` says what a player can set an opponent to. A puzzle can
 * perfectly well be harder than the strongest bot: that is what the top band,
 * open-ended at `Infinity`, is for. Clamping ratings to the bot ceiling instead
 * squashed every above-ceiling puzzle onto the exact same number — 74 checkers
 * puzzles all rated 2000 — which passes a count check and gives the Master band
 * zero spread, so it reads as full while containing one difficulty repeated.
 *
 * The scale therefore runs one tier's width past the ladder at the top, which
 * is exactly as far as the extrapolation in `botRatingFromCurve` can reach. The
 * floor stays where it is: nothing below it is meaningful.
 */
export const PUZZLE_RATING_BOUNDS: Record<PuzzleGame, { min: number; max: number }> = {
  chess: ratingBounds('chess'),
  checkers: ratingBounds('checkers'),
  reversi: ratingBounds('reversi'),
  go: ratingBounds('go'),
};

function ratingBounds(game: RatedGameId): { min: number; max: number } {
  const tiers = BOT_TIERS[game];
  const topGap = tiers[tiers.length - 1].elo - tiers[tiers.length - 2].elo;
  return { min: BOT_ELO_BOUNDS[game].min, max: BOT_ELO_BOUNDS[game].max + topGap };
}

// ---------------------------------------------------------------------------
// Bot scale → human scale
// ---------------------------------------------------------------------------

export interface CalibrationKnot {
  /** A bot rating, at one of the six tier ELOs. */
  bot: number;
  /** The human rating that bot rating corresponds to. */
  human: number;
  /** Sample puzzles behind this knot. 0 means it was carried, not measured. */
  samples: number;
}

export interface CalibrationSample {
  bot: number;
  human: number;
}

/**
 * Fit the monotone piecewise-linear map from bot ratings to human ratings.
 *
 * Knots sit at the six tier ELOs rather than anywhere the fit likes, because
 * those are the only bot ratings that are directly observed — everything
 * between them is already an interpolation, and putting knots there would be
 * fitting the interpolation rather than the data.
 *
 * Deliberately not a polynomial. An unconstrained fit goes non-monotone at the
 * sparse ends, and a rating map that runs backwards rates a harder puzzle lower
 * — a defect no amount of goodness-of-fit makes acceptable.
 */
export function fitCalibration(
  tiers: readonly number[],
  samples: readonly CalibrationSample[],
): CalibrationKnot[] {
  const buckets = tiers.map(() => [] as number[]);
  for (const s of samples) {
    // Nearest knot, so every sample informs exactly one.
    let best = 0;
    for (let i = 1; i < tiers.length; i++) {
      if (Math.abs(s.bot - tiers[i]) < Math.abs(s.bot - tiers[best])) best = i;
    }
    buckets[best].push(s.human);
  }

  // Knots with no samples are DROPPED rather than filled in. An invented knot
  // is indistinguishable from a measured one once it is in the artifact, and
  // interpolating across the gap is both honest and what the reader expects.
  const present = tiers
    .map((elo, i) => ({ elo, humans: buckets[i] }))
    .filter((k) => k.humans.length > 0);

  if (present.length === 0) return [];

  const means = present.map((k) => k.humans.reduce((a, b) => a + b, 0) / k.humans.length);
  const monotone = isotonic(means);

  return present.map((k, i) => ({
    bot: k.elo,
    human: Math.round(monotone[i]),
    samples: k.humans.length,
  }));
}

/**
 * Apply a fitted map.
 *
 * Outside the knot range the nearest segment's slope is extended rather than
 * the end value repeated: clamping would map every puzzle above the top knot to
 * one rating, collapsing the hardest band into a single point. The result is
 * then clamped to the game's own ELO bounds, so an extrapolation cannot invent
 * a rating the game does not offer a bot at.
 */
export function humanRating(
  game: PuzzleGame,
  botRating: number,
  knots: readonly CalibrationKnot[],
): number {
  const bounds = PUZZLE_RATING_BOUNDS[game];
  if (knots.length === 0) return Math.round(clamp(botRating, bounds.min, bounds.max));
  if (knots.length === 1) return Math.round(clamp(knots[0].human, bounds.min, bounds.max));

  const sorted = [...knots].sort((a, b) => a.bot - b.bot);

  let lo = 0;
  let hi = sorted.length - 1;
  if (botRating <= sorted[0].bot) {
    hi = 1;
    lo = 0;
  } else if (botRating >= sorted[sorted.length - 1].bot) {
    lo = sorted.length - 2;
    hi = sorted.length - 1;
  } else {
    for (let i = 0; i < sorted.length - 1; i++) {
      if (botRating >= sorted[i].bot && botRating <= sorted[i + 1].bot) {
        lo = i;
        hi = i + 1;
        break;
      }
    }
  }

  const span = sorted[hi].bot - sorted[lo].bot;
  // Two knots at the same bot rating cannot be interpolated between; the fit
  // never produces them, but a hand-edited artifact could.
  const t = span === 0 ? 0 : (botRating - sorted[lo].bot) / span;
  const value = sorted[lo].human + t * (sorted[hi].human - sorted[lo].human);
  return Math.round(clamp(value, bounds.min, bounds.max));
}

function clamp(v: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, v));
}

// ---------------------------------------------------------------------------
// Go — structural rating
// ---------------------------------------------------------------------------

/**
 * What a Go problem's difficulty is read from, since its bot cannot read it.
 *
 * Every one of these is a property of the *problem as composed*, available from
 * the exhaustive solver that already proves the puzzle correct — so rating a Go
 * puzzle costs no extra search and is perfectly deterministic.
 *
 * **The forced line's length was a fourth feature, and was removed.** Fitted to
 * the fourteen hand-rated problems it came back with a *negative* coefficient —
 * a longer forced line making a problem easier — which is not a claim about
 * difficulty anyone should ship. Dropping it changed the mean absolute error by
 * nothing at all (66 either way, measured), so it was carrying noise, not
 * signal, and five coefficients over fourteen points is exactly where that
 * happens. What is left is three features whose signs all mean what they say:
 * a bigger space, a bigger search and more ways to go wrong are all harder.
 */
export interface GoStructuralFeatures {
  /** Points in the fight. A bigger region is a bigger read. */
  regionSize: number;
  /** Positions the solver visited, log-scaled — the search's own cost. */
  logNodes: number;
  /**
   * First moves inside the region that do NOT work.
   *
   * The count of ways to go wrong, which is the part of difficulty the other
   * three features miss entirely: a five-point eye space with one vital point
   * and eleven refutations is harder than one with three answers that all work.
   */
  losingMoves: number;
}

export interface GoStructuralModel {
  intercept: number;
  regionSize: number;
  logNodes: number;
  losingMoves: number;
}

export function goStructuralRating(
  features: GoStructuralFeatures,
  model: GoStructuralModel,
): number {
  const raw =
    model.intercept +
    model.regionSize * features.regionSize +
    model.logNodes * features.logNodes +
    model.losingMoves * features.losingMoves;
  const bounds = PUZZLE_RATING_BOUNDS.go;
  return Math.round(clamp(raw, bounds.min, bounds.max));
}

// ---------------------------------------------------------------------------
// The shipped map
// ---------------------------------------------------------------------------

export const CALIBRATION_TIERS: Record<PuzzleGame, readonly number[]> = {
  chess: BOT_TIERS.chess.map((t) => t.elo),
  checkers: BOT_TIERS.checkers.map((t) => t.elo),
  reversi: BOT_TIERS.reversi.map((t) => t.elo),
  go: BOT_TIERS.go.map((t) => t.elo),
};

// ---------------------------------------------------------------------------
// Least squares — the Go structural fit
// ---------------------------------------------------------------------------

/**
 * Ridge-regularised least squares: solve `(XᵀX + λI)b = Xᵀy` for `b`.
 *
 * The ridge term is not decoration. The Go model is fitted to **fourteen**
 * hand-rated problems on four features, two of which — region size and the
 * log of the solver's node count — measure very nearly the same thing, because
 * a wider region is exactly what makes the search bigger. `XᵀX` is therefore
 * close to singular, and an unregularised solve answers with enormous
 * coefficients of opposite sign that fit those fourteen points beautifully and
 * predict nothing. λ trades a little fit for a model that generalises, which is
 * the entire purpose here.
 *
 * Add your own bias column; this fits exactly the columns it is given.
 */
export function fitLeastSquares(
  design: readonly (readonly number[])[],
  targets: readonly number[],
  lambda = 1,
): number[] {
  const n = design.length;
  if (n === 0 || targets.length !== n) {
    throw new Error('fitLeastSquares: design and targets must be the same non-zero length');
  }
  const p = design[0].length;

  // Normal equations, built directly — p is tiny (five here), so there is no
  // reason to reach for a decomposition.
  const a: number[][] = Array.from({ length: p }, () => Array<number>(p).fill(0));
  const b: number[] = Array<number>(p).fill(0);
  for (let i = 0; i < n; i++) {
    for (let j = 0; j < p; j++) {
      b[j] += design[i][j] * targets[i];
      for (let k = 0; k < p; k++) a[j][k] += design[i][j] * design[i][k];
    }
  }
  for (let j = 0; j < p; j++) a[j][j] += lambda;

  // Gauss-Jordan with partial pivoting.
  for (let col = 0; col < p; col++) {
    let pivot = col;
    for (let row = col + 1; row < p; row++) {
      if (Math.abs(a[row][col]) > Math.abs(a[pivot][col])) pivot = row;
    }
    if (Math.abs(a[pivot][col]) < 1e-12) continue; // column carries no information
    [a[col], a[pivot]] = [a[pivot], a[col]];
    [b[col], b[pivot]] = [b[pivot], b[col]];

    const d = a[col][col];
    for (let k = col; k < p; k++) a[col][k] /= d;
    b[col] /= d;

    for (let row = 0; row < p; row++) {
      if (row === col) continue;
      const factor = a[row][col];
      if (factor === 0) continue;
      for (let k = col; k < p; k++) a[row][k] -= factor * a[col][k];
      b[row] -= factor * b[col];
    }
  }
  return b;
}

/** The design row for one Go problem, in the order `GoStructuralModel` names. */
export function goDesignRow(f: GoStructuralFeatures): number[] {
  return [1, f.regionSize, f.logNodes, f.losingMoves];
}

export function goModelFrom(coefficients: readonly number[]): GoStructuralModel {
  const [intercept, regionSize, logNodes, losingMoves] = coefficients;
  return { intercept, regionSize, logNodes, losingMoves };
}
